version: '3.2'
services:
  lizmap:
    image: opengisch/docker-lizmap:3.3rc2
    restart: on-failure
    ports:
     - 80:80
     - 443:443
    volumes:
     - project:/io/qgis_projects
     - var:/var/www/lizmap/var
    depends_on:
      - postgis
      - qgiserver
      - redis
    links:
     - qgiserver:qgiserver
     - redis:redis
     
  qgiserver:
    image: "openquake/qgis-server:3.6.3-ubuntu"
      environment:
        QGIS_SERVER_PARALLEL_RENDERING: "true"
        QGIS_SERVER_MAX_THREADS: 4
        QGIS_SERVER_LOG_LEVEL: 0
        # needs to be defined as fcgi_param in nginx.conf
        # PGSERVICEFILE: /io/.pg_service.conf
    restart: on-failure
    volumes:
      - project:/io/qgis_projects
    expose:
      - 80
      
  redis:
    image: redis:alpine
    restart: on-failure
    volumes:
      - redis:/data
    expose:
      - 6379

  postgis:
    image: kartoza/postgis:11.0-2.5
    ports:
      - 5432:5432
    expose:
      - 5432
    entrypoint: >
      bash -c "wget -N -P / https://raw.githubusercontent.com/jancelin/docker-postgis/master/setup-database.sh &&
               wget -N -P /home https://github.com/jancelin/docker-postgis/raw/master/geopoppy.sql &&
               /docker-entrypoint.sh"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=docker
      - POSTGRES_DBNAME=geopoppy
      - POSTGRES_DUMP=geopoppy.sql
    volumes:
      - postgres:/var/lib/postgresql
      
  pgadmin4:
    image: chorss/docker-pgadmin4
    restart: on-failure
    ports:
      - 5050:5050
    volumes:
      - pgadmin4:/data
      
  portainer:
    image: portainer/portainer
    restart: always
    ports:
     - 9000:9000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer:/data
     
  cloud:
    image: coderaiser/cloudcmd:latest-alpine
    restart: always
    ports:
      - 8000:8000
    volumes:
#      - ~:/root
      - project:/mnt/fs
     
volumes:
   portainer:
   pgadmin4:
   postgres:
   redis:
   var:
   project:
   

